# Dockerfile for Backend
FROM openjdk:17-jdk-alpine

# Define the working directory inside the container
WORKDIR /app

# Copy the Maven build file and source code
COPY . /app

# Package the backend project (Maven command to build)
RUN ./mvnw clean package -DskipTests

# Expose the port for the backend (e.g., 8081)
EXPOSE 8081

# Run the JAR file generated by Maven
CMD ["java", "-jar", "target/backend.jar"]