services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    networks:
      - frontend_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8081:8081"
    networks:
      - frontend_network
      - backend_network
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - backend_network

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
